#!/usr/bin/env python3

import copy
import json
import os
import sys

import yaml
from packaging import version

product = ''
kubeversion = ''

def have_kubeversion(required_version):
    global kubeversion
    return version.parse(kubeversion) >= version.parse(required_version)

old_pro_crds = {
    'Filter',
    'FilterPolicy',
    'RateLimit'}

old_oss_crds = {
    'AuthService',
    'ConsulResolver',
    'KubernetesEndpointResolver',
    'KubernetesServiceResolver',
    'LogService',
    'Mapping',
    'Module',
    'RateLimitService',
    'TCPMapping',
    'TLSContext',
    'TracingService'}

def fix_crd(crd):
    global product

    # sanity check
    if crd['kind'] != 'CustomResourceDefinition' or not crd['apiVersion'].startswith('apiextensions.k8s.io/'):
        raise f"not a CRD: {crd}"

    # fix apiVersion
    if have_kubeversion('1.16'):
        crd['apiVersion'] = 'apiextensions.k8s.io/v1'
    else:
        crd['apiVersion'] = 'apiextensions.k8s.io/v1beta1'

    # fix CRD versions
    if have_kubeversion('1.11'):
        if crd['apiVersion'] == 'apiextensions.k8s.io/v1':
            if 'version' in crd['spec']:
                del crd['spec']['version']
        else:
            # Set this to 'null' instead of just not setting it,
            # because some apiserver versions (like 1.14.10-gke.27)
            # will auto-populate it, and that makes upgrades
            # troublesome if `.versions[0]` changes.
            crd['spec']['version'] = None

        # Note: versions are sorted newest-first/oldest-last.
        if crd['spec']['names']['kind'] in old_pro_crds:
            crd['spec']['versions'] = [
                { 'name': 'v2', 'served': True, 'storage': True },
                { 'name': 'v1beta2', 'served': True, 'storage': False },
                { 'name': 'v1beta1', 'served': True, 'storage': False },
            ]
        elif crd['spec']['names']['kind'] in old_oss_crds:
            crd['spec']['versions'] = [
                { 'name': 'v2', 'served': True, 'storage': True },
                { 'name': 'v1', 'served': True, 'storage': False },
            ]
        else:
            crd['spec']['versions'] = [
                { 'name': 'v2', 'served': True, 'storage': True },
            ]
    else:
        if 'versions' in crd['spec']:
            del crd['spec']['versions']
        crd['spec']['version'] = 'v2'
        def handle_dict(d):
            if 'additionalProperties' in d:
                del d['additionalProperties']
            for val in d.values():
                if isinstance(val, dict):
                    handle_dict(val)
        handle_dict(crd['spec'])

    # fix labels
    labels = crd['metadata'].get('labels', {})
    if product:
        labels['product'] = product
    elif 'product' in labels:
        del labels['product']
    crd['metadata']['labels'] = labels

    # fix categories
    categories = crd['spec']['names'].get('categories', [])
    if 'ambassador-crds' not in categories:
        # sys.stderr.write(f"CRD {crd['metadata']['name']} missing ambassador-crds category\n")
        categories.append('ambassador-crds')
    crd['spec']['names']['categories'] = categories

    # fix status
    #
    # Are you kidding me: controller-gen generates CRDs with status
    # set... even though the apiserver will entirely ignore the status
    # if you try to set it on the broader parent resource.  But! As of
    # controller-gen 0.3.0, it generates a status that kubectl's
    # client-side validation will reject.  So remove the statuses that
    # should never have been there anyway, so that the tools that are
    # to stupid to know to ignore them don't trip up on them.
    if 'status' in crd:
        del crd['status']

def main():
    global product
    global kubeversion

    product = sys.argv[1]
    kubeversion = sys.argv[2]
    inputfiles = sys.argv[3:] or ['/dev/stdin']

    crds = []
    for in_path in inputfiles:
        crds += list(yaml.safe_load_all(open(in_path, "r")))

    for crd in crds:
        fix_crd(crd)

    print("# GENERATED FILE: edits made by hand will not be preserved.")
    print("---")
    print(yaml.safe_dump_all(crds), end='')

if __name__ == "__main__":
    main()
