{
 "title": "AES Domains",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Domain registrations",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Number of domains" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(creation_time,1m,previous),\n  sum(count(id)) OVER (ORDER BY $__timeGroup(creation_time,1m,previous)) AS \"Number of domains\"\nFROM aes_domains\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(creation_time,1m,0),\n  (CASE WHEN count(id) >= lag(count(id)) OVER (ORDER BY $__timeGroup(creation_time,1m,0)) THEN count(id) - lag(count(id)) OVER (ORDER BY $__timeGroup(creation_time,1m,0)) WHEN lag(count(id)) OVER (ORDER BY $__timeGroup(creation_time,1m,0)) IS NULL THEN NULL ELSE count(id) END) AS \"Increase in number of domains\"\nFROM aes_domains\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Domain registrations in the last 7 days",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Number of domains" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(creation_time,1m,previous),\n  sum(count(id)) OVER (ORDER BY $__timeGroup(creation_time,1m,previous)) AS \"Number of domains\"\nFROM aes_domains\nWHERE\n  $__timeFilter(creation_time)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  }
 ]
}
{
 "title": "Crash Reports",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Warning",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "content": "\n# Authentication\n\n### Please make sure you are **authenticated** with [Amazon Web Services](https://accounts.google.com/o/saml2/initsso?idpid=C00lzgcpx&spid=951020006139&forceauthn=false) before attempting to download logs from crash reports.\n\nThe stored log files are not publicly readable, therefore you must first authenticate with AWS.\n\n\n\n"
  },
  {
   "title": "Crash Reports",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT creation_time as time, metadata->>'Product' as product, metadata->>'ProductVersion' as version, metadata->>'AESVersion' as aes_version, id, metadata->>'Error' as error from crash_report"
    }
   ]
  }
 ]
}