FROM node:carbon-alpine

LABEL PROJECT_REPO_URL         = "git@github.com:datawire/ambassador.git" \
      PROJECT_REPO_BROWSER_URL = "https://github.com/datawire/ambassador" \
      DESCRIPTION              = "Ambassador REST Service" \
      VENDOR                   = "Datawire" \
      VENDOR_URL               = "https://datawire.io/"

ENV NODE_ENV production

WORKDIR /app

ADD . .
RUN npm install

CMD ["npm", "start"]
