mypy-server-stop: venv
	venv/bin/dmypy stop
.PHONY: mypy-server-stop

mypy-server: venv
	@if ! venv/bin/dmypy status >/dev/null; then \
		venv/bin/dmypy start -- --use-fine-grained-cache --follow-imports=skip --ignore-missing-imports ;\
		echo "Started mypy server" ;\
	fi
.PHONY: mypy-server

mypy: mypy-server
	time venv/bin/dmypy check python
.PHONY: mypy
