{
 "title": "APro Load testing",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Memory usage (generators)",
   "type": "graph",
   "description": "Memory usage for all containers in namespace=default",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_name!=\"\",container_name!=\"POD\",namespace=\"default\",node=~\"gke-kube-sbx-loadtest-generators-.*\"}",
     "legendFormat": "{{pod_name}}/{{container_name}} ({{node}})"
    }
   ]
  },
  {
   "title": "Memory usage (backends)",
   "type": "graph",
   "description": "Memory usage for all containers in namespace=default",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_name!=\"\",container_name!=\"POD\",namespace=\"default\",node=~\"gke-kube-sbx-loadtest-backends-.*\"}",
     "legendFormat": "{{pod_name}}/{{container_name}} ({{node}})"
    }
   ]
  },
  {
   "title": "Memory usage (ingress)",
   "type": "graph",
   "description": "Memory usage for all containers in namespace=default",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_name!=\"\",container_name!=\"POD\",namespace=\"default\",node=~\"gke-kube-sbx-loadtest-ingress-.*\"}",
     "legendFormat": "{{pod_name}}/{{container_name}} ({{node}})"
    }
   ]
  }
 ]
}