// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: envoy/extensions/transport_sockets/starttls/v3/starttls.proto

package envoy_extensions_transport_sockets_starttls_v3

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// Validate checks the field values on StartTlsConfig with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *StartTlsConfig) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetCleartextSocketConfig()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return StartTlsConfigValidationError{
				field:  "CleartextSocketConfig",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetTlsSocketConfig() == nil {
		return StartTlsConfigValidationError{
			field:  "TlsSocketConfig",
			reason: "value is required",
		}
	}

	if v, ok := interface{}(m.GetTlsSocketConfig()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return StartTlsConfigValidationError{
				field:  "TlsSocketConfig",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// StartTlsConfigValidationError is the validation error returned by
// StartTlsConfig.Validate if the designated constraints aren't met.
type StartTlsConfigValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StartTlsConfigValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StartTlsConfigValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StartTlsConfigValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StartTlsConfigValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StartTlsConfigValidationError) ErrorName() string { return "StartTlsConfigValidationError" }

// Error satisfies the builtin error interface
func (e StartTlsConfigValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStartTlsConfig.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StartTlsConfigValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StartTlsConfigValidationError{}
