#!/usr/bin/env bash
set -x
# Save the images
docker image ls --filter=dangling=false --format='{{ .Repository }}:{{ .Tag }}' | xargs docker image save > docker/images.tar
# Save the cache volume
docker run \
  --rm \
  --volumes-from=$(cat docker/container.txt) \
  --volume="$PWD/docker":/mnt \
  --user=root \
  --workdir=/home/dw \
  --entrypoint=tar $(cat docker/snapshot.docker) -cf /mnt/volume.tar .
