#!/usr/bin/env bash

# Copyright 2018-2019 Datawire. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License

set -o errexit

# Don't bother trying to build the website if GH_TOKEN is unset (as it will
# be for a community PR).
if [ -z "$GH_TOKEN" ]; then
	echo '[pr-build-website-preview] skipping: GH_TOKEN is not set'
	exit 0
fi

set -o nounset
set -o xtrace

website_branch=${1:-master}

rm -rf "/tmp/getambassador.io-$website_branch"
git clone --single-branch --branch="$website_branch" https://d6e-automaton:${GH_TOKEN}@github.com/datawire/getambassador.io.git "/tmp/getambassador.io-$website_branch"
cd "/tmp/getambassador.io-$website_branch"
git submodule update --init --reference="$TRAVIS_BUILD_DIR"
git -C submodules/latest checkout "$TRAVIS_COMMIT"
git -C submodules/1.4 checkout "$TRAVIS_COMMIT"
npm install
npm run build
