#!/usr/bin/env bash

# Copyright 2018-2019 Datawire. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License

set -o errexit
set -o nounset

case "${TRAVIS_PULL_REQUEST_SHA:+${TRAVIS_BRANCH:-}}" in
	master) submodule=content;;
	early-access) submodule=content-ea/early-access;;
	*)
		echo "[pr-build-website-preview] skipping: not a PR in to 'master' or 'early-access'"
		exit 0
		;;
esac

set -o verbose

# Don't trust $TRAVIS_COMMIT, use $(git rev-parse HEAD) instead.
#
# For PRs, it's often set to a stale merge commit that isn't fetched,
# instead of the actual commit pointed to by refs/pull/NNN/merge which
# is checked out.  For example, on
# <https://travis-ci.org/datawire/ambassador-docs/builds/629117603>,
# the webui says         it's testing commit cb8dc0029465119ada1ee9222539c825f5a7c015,
# and TRAVIS_COMMIT says it's testing commit cb8dc0029465119ada1ee9222539c825f5a7c015,
# but in fact            it's testing commit d23659347cd125267b079f2f7900c3e1b032ea4b.
docs_commit=$(git rev-parse HEAD)

rm -rf /tmp/getambassador.io
git clone https://d6e-automaton:${GH_TOKEN}@github.com/datawire/getambassador.io.git /tmp/getambassador.io
cd /tmp/getambassador.io
git submodule update --init --reference="$TRAVIS_BUILD_DIR"
git -C "$submodule" checkout "$docs_commit"
npm install
npm run build
