#!/usr/bin/env bash

set -o errexit
set -o nounset

printf "== Begin: build-docs.sh ==\n"

# From ./ambassador/.ci/website-preview-build

set -o xtrace
set -o verbose

build_dir=$(pwd)

rm -rf "/tmp/getambassador.io"
git clone --single-branch https://d6e-automaton:${GH_TOKEN}@github.com/datawire/getambassador.io.git "/tmp/getambassador.io"
cd "/tmp/getambassador.io"
git submodule update --init

# Swap out the "latest" info for our stuff.
rm -rf submodules/latest
mkdir submodules/latest
cp -prv $build_dir/ambassador/docs submodules/latest/docs

# Since we only want the one preview, toss out links to other versions from the header...
sed -e '/to="\/docs\/[0-9]/d' < src/components/Header/Header.js > H2.js && mv H2.js src/components/Header/Header.js

# # ...and in docs-structure.
# rm -f docs-structure/docs/[0-9]*

npm install
npm run build

# From ./ambassador/.ci/website-preview-publish

if ! [[ -d /tmp/getambassador.io/public ]]; then
	echo '[website-preview-publish] skipping: website preview was not built'
	exit 0
fi

npm install netlify-cli -g

netlify deploy \
	--dir="/tmp/getambassador.io/public" \
	--message="ambassador.git preview" \
	--site=1d6f5395-6386-49af-8b47-e85aa28488f8 \
	--auth="${NETLIFY_AUTH_TOKEN}" \
	--json \
	> /tmp/netlify-deploy.json

cat /tmp/netlify-deploy.json

cat >/tmp/github-status.json <<EOF
{
  "context": "website-preview",
  "state": "success",
  "target_url": $(jq .deploy_url </tmp/netlify-deploy.json),
  "description": "Website preview"
}
EOF

curl --fail \
	-H "Accept: application/json" \
	-H "Content-Type: application/json" \
	-X POST \
	--data '@/tmp/github-status.json' \
	"https://${GH_TOKEN}@api.github.com/repos/datawire/apro/statuses/${CIRCLE_SHA1}"

export GH_TOKEN='' # Don't post to GitHub; set an exit code instead
${source_dir}/.ci/website-preview-blc
