FROM datawire/qotm:1.1 as qotm

FROM {{ambassador-image}}

WORKDIR /demo

# Copy in the qotm service...
COPY --from=qotm /service/qotm/qotm.py .

# ...and the auth service...
COPY simple-auth-server.py .

# ...and the demo config.
COPY config /etc/ambassador-config

# Finally set an endpoint.

# COPY the entrypoint script and make it runnable.
COPY entrypoint.sh .
RUN chmod 755 entrypoint.sh

ENTRYPOINT [ "./entrypoint.sh" ]
