#!/usr/bin/env bash

# Copyright 2018-2019 Datawire. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License

set -o errexit
set -o nounset

website_branch=${1:-master}
pr_branch=${TRAVIS_PULL_REQUEST_SHA:+${TRAVIS_BRANCH:-}}

echo "[pr-build-website-preview] website branch ${website_branch}, PR branch ${pr_branch}"

case "$pr_branch" in
	master) submodule=content;;
	early-access)
		case "$website_branch" in
			master) submodule=content-ea/early-access;;
			Edge-stack-update) submodule=content;;
			*)
				echo "[pr-build-website-preview] skipping: wut: $website_branch"
				exit 1
				;;
		esac
		;;
	*)
		if [[ -z "$TRAVIS_PULL_REQUEST_SHA" ]]; then
			echo "[pr-build-website-preview] skipping: not a PR"
		else
			echo "[pr-build-website-preview] skipping: is a PR, but is in to '${TRAVIS_BRANCH}', not 'master' or 'early-access'"
		fi
		exit 0
		;;
esac

set -o xtrace

rm -rf "/tmp/getambassador.io-$website_branch"
git clone --single-branch --branch="$website_branch" https://d6e-automaton:${GH_TOKEN}@github.com/datawire/getambassador.io.git "/tmp/getambassador.io-$website_branch"
cd "/tmp/getambassador.io-$website_branch"
git submodule update --init --reference="$TRAVIS_BUILD_DIR"
git -C "$submodule" checkout "$TRAVIS_COMMIT"
npm install
npm run build
