# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AuthService.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='AuthService.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11\x41uthService.proto\"\x8d\x05\n\x0b\x41uthService\x12\x12\n\napiVersion\x18\x01 \x01(\t\x12\x12\n\ngeneration\x18\x02 \x01(\x05\x12\x0c\n\x04kind\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x15\n\rambassador_id\x18\x05 \x03(\t\x12\x14\n\x0c\x61uth_service\x18\x06 \x01(\t\x12\x13\n\x0bpath_prefix\x18\x07 \x01(\t\x12\x15\n\x0btls_context\x18\x08 \x01(\tH\x00\x12\r\n\x03tls\x18\t \x01(\x08H\x00\x12&\n\x05proto\x18\n \x01(\x0e\x32\x17.AuthService.AuthProtos\x12\x12\n\ntimeout_ms\x18\x0b \x01(\x05\x12\x1f\n\x17\x61llowed_request_headers\x18\x0c \x03(\t\x12%\n\x1d\x61llowed_authorization_headers\x18\r \x03(\t\x12\x1a\n\x12\x61llow_request_body\x18\x0e \x01(\x08\x12\x1b\n\x13\x61\x64\x64_linkerd_headers\x18\x0f \x01(\x08\x12\x1a\n\x12\x66\x61ilure_mode_allow\x18\x10 \x01(\x08\x12\x32\n\x0cinclude_body\x18\x11 \x01(\x0b\x32\x1c.AuthService.AuthIncludeBody\x12\x37\n\x0fstatus_on_error\x18\x12 \x01(\x0b\x32\x1e.AuthService.AuthStatusOnError\x1a;\n\x0f\x41uthIncludeBody\x12\x11\n\tmax_bytes\x18\x01 \x01(\x05\x12\x15\n\rallow_partial\x18\x02 \x01(\x08\x1a!\n\x11\x41uthStatusOnError\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\" \n\nAuthProtos\x12\x08\n\x04HTTP\x10\x00\x12\x08\n\x04GRPC\x10\x01\x42\n\n\x08tls_infob\x06proto3')
)



_AUTHSERVICE_AUTHPROTOS = _descriptor.EnumDescriptor(
  name='AuthProtos',
  full_name='AuthService.AuthProtos',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='HTTP', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GRPC', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=631,
  serialized_end=663,
)
_sym_db.RegisterEnumDescriptor(_AUTHSERVICE_AUTHPROTOS)


_AUTHSERVICE_AUTHINCLUDEBODY = _descriptor.Descriptor(
  name='AuthIncludeBody',
  full_name='AuthService.AuthIncludeBody',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='max_bytes', full_name='AuthService.AuthIncludeBody.max_bytes', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='allow_partial', full_name='AuthService.AuthIncludeBody.allow_partial', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=535,
  serialized_end=594,
)

_AUTHSERVICE_AUTHSTATUSONERROR = _descriptor.Descriptor(
  name='AuthStatusOnError',
  full_name='AuthService.AuthStatusOnError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='AuthService.AuthStatusOnError.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=596,
  serialized_end=629,
)

_AUTHSERVICE = _descriptor.Descriptor(
  name='AuthService',
  full_name='AuthService',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='apiVersion', full_name='AuthService.apiVersion', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='generation', full_name='AuthService.generation', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kind', full_name='AuthService.kind', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='AuthService.name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ambassador_id', full_name='AuthService.ambassador_id', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='auth_service', full_name='AuthService.auth_service', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='path_prefix', full_name='AuthService.path_prefix', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tls_context', full_name='AuthService.tls_context', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tls', full_name='AuthService.tls', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='proto', full_name='AuthService.proto', index=9,
      number=10, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeout_ms', full_name='AuthService.timeout_ms', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='allowed_request_headers', full_name='AuthService.allowed_request_headers', index=11,
      number=12, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='allowed_authorization_headers', full_name='AuthService.allowed_authorization_headers', index=12,
      number=13, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='allow_request_body', full_name='AuthService.allow_request_body', index=13,
      number=14, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='add_linkerd_headers', full_name='AuthService.add_linkerd_headers', index=14,
      number=15, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='failure_mode_allow', full_name='AuthService.failure_mode_allow', index=15,
      number=16, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='include_body', full_name='AuthService.include_body', index=16,
      number=17, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status_on_error', full_name='AuthService.status_on_error', index=17,
      number=18, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_AUTHSERVICE_AUTHINCLUDEBODY, _AUTHSERVICE_AUTHSTATUSONERROR, ],
  enum_types=[
    _AUTHSERVICE_AUTHPROTOS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='tls_info', full_name='AuthService.tls_info',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=22,
  serialized_end=675,
)

_AUTHSERVICE_AUTHINCLUDEBODY.containing_type = _AUTHSERVICE
_AUTHSERVICE_AUTHSTATUSONERROR.containing_type = _AUTHSERVICE
_AUTHSERVICE.fields_by_name['proto'].enum_type = _AUTHSERVICE_AUTHPROTOS
_AUTHSERVICE.fields_by_name['include_body'].message_type = _AUTHSERVICE_AUTHINCLUDEBODY
_AUTHSERVICE.fields_by_name['status_on_error'].message_type = _AUTHSERVICE_AUTHSTATUSONERROR
_AUTHSERVICE_AUTHPROTOS.containing_type = _AUTHSERVICE
_AUTHSERVICE.oneofs_by_name['tls_info'].fields.append(
  _AUTHSERVICE.fields_by_name['tls_context'])
_AUTHSERVICE.fields_by_name['tls_context'].containing_oneof = _AUTHSERVICE.oneofs_by_name['tls_info']
_AUTHSERVICE.oneofs_by_name['tls_info'].fields.append(
  _AUTHSERVICE.fields_by_name['tls'])
_AUTHSERVICE.fields_by_name['tls'].containing_oneof = _AUTHSERVICE.oneofs_by_name['tls_info']
DESCRIPTOR.message_types_by_name['AuthService'] = _AUTHSERVICE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AuthService = _reflection.GeneratedProtocolMessageType('AuthService', (_message.Message,), {

  'AuthIncludeBody' : _reflection.GeneratedProtocolMessageType('AuthIncludeBody', (_message.Message,), {
    'DESCRIPTOR' : _AUTHSERVICE_AUTHINCLUDEBODY,
    '__module__' : 'AuthService_pb2'
    # @@protoc_insertion_point(class_scope:AuthService.AuthIncludeBody)
    })
  ,

  'AuthStatusOnError' : _reflection.GeneratedProtocolMessageType('AuthStatusOnError', (_message.Message,), {
    'DESCRIPTOR' : _AUTHSERVICE_AUTHSTATUSONERROR,
    '__module__' : 'AuthService_pb2'
    # @@protoc_insertion_point(class_scope:AuthService.AuthStatusOnError)
    })
  ,
  'DESCRIPTOR' : _AUTHSERVICE,
  '__module__' : 'AuthService_pb2'
  # @@protoc_insertion_point(class_scope:AuthService)
  })
_sym_db.RegisterMessage(AuthService)
_sym_db.RegisterMessage(AuthService.AuthIncludeBody)
_sym_db.RegisterMessage(AuthService.AuthStatusOnError)


# @@protoc_insertion_point(module_scope)
