#!/bin/bash

set -e

CURR_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
[ -d "$CURR_DIR" ] || { echo "FATAL: no current dir (maybe running in zsh?)";  exit 1; }
rc_tag=$1
if [[ -z "${rc_tag}" ]] ; then
    echo "ERROR: rc_tag must be first argument"
    exit 1
fi

commit=$(git rev-parse HEAD)

${CURR_DIR}/release-wait-for-commit --commit $commit --s3-key dev-builds

git tag -m v$rc_tag -a v$rc_tag
git push origin v$rc_tag

${CURR_DIR}/release-wait-for-rc-artifacts --rc-tag $rc_tag --release-registry ${RELEASE_REGISTRY} --image-name ${IMAGE_NAME}
