#!/usr/bin/env python3
"""Mirror GA Docker images from one Docker registry to several others.

"""

import os.path
import sys

from lib import mirror_artifacts, re_ga


def main(ga_ver: str) -> int:
    mirror_artifacts.main([ga_ver])
    return 0


if __name__ == '__main__':
    if len(sys.argv) != 2 or not re_ga.match(sys.argv[1]):
        sys.stderr.write(f"Usage: {os.path.basename(sys.argv[0])} X.Y.Z\n")
        sys.exit(2)
    sys.exit(main(ga_ver=sys.argv[1]))
