#!/bin/bash

set -ex

if [ -n "$(git status --porcelain)" ]; then
    echo "Local tree is dirty, exiting"
    exit 1
fi
git fetch

UPSTREAM=${1:-'@{u}'}
LOCAL=$(git rev-parse @)
REMOTE=$(git rev-parse "$UPSTREAM")
BASE=$(git merge-base @ "$UPSTREAM")

if [ $LOCAL = $REMOTE ]; then
    echo "Up-to-date"
elif [ $LOCAL = $BASE ]; then
    echo "Need to pull"
    exit 1
elif [ $REMOTE = $BASE ]; then
    echo "Local is ahead of remote, push your local changes to continue"
    exit 1
else
    echo "Local is out of sync with remote, resolve this before continuing"
    exit 1
fi

git merge origin/master

git pr create --title "Repatriate"
