#!/usr/bin/env python3
"""Waits for commit to show up in s3
"""

import argparse
import http.client
import sys
import time
from lib import ansiterm


def main(commit: str, s3_key: str) -> int:
    print(f"{ansiterm.sgr.bold.fg_cyn}==> Waiting for commit {commit} to show up in s3://datawire-static-files/{s3_key}/")
    print(f"    Check Circle CI if you would like to check progress:")
    print(f"        https://app.circleci.com/pipelines/github/emissary-ingress/emissary{ansiterm.sgr.reset}")
    s3_url = f"datawire-static-files.s3.amazonaws.com"
    while True:
        conn = http.client.HTTPSConnection(s3_url)
        conn.request("GET", f"/{s3_key}/{commit}")
        r1 = conn.getresponse()
        if r1.status == 200:
            print(f"{ansiterm.sgr.bold.fg_grn}==> Commit {commit} found in S3!{ansiterm.sgr}")
            return 0
        print(f"    {ansiterm.sgr.fg_red}Commit {commit} still not in S3, sleeping before trying again.{ansiterm.sgr}")
        time.sleep(30)
    return 1


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Wait for commit to show up in s3')
    parser.add_argument('--commit', required=True)
    parser.add_argument('--s3-key', default="dev-builds")
    args = parser.parse_args()

    sys.exit(main(
        commit=args.commit,
        s3_key=args.s3_key,
    ))
