package(default_visibility = ["//visibility:public"])
load("@my_deps//:requirements.bzl", "requirement")

py_library(
    name = "test_multi",
    srcs = ["test_multi.py"],
    deps = [requirement("multi")],
)
