package(default_visibility = ["//visibility:public"])
load("@ambassador_pip//:requirements.bzl", "requirement")

py_test(
    name = "test_multi",
    srcs = ["test_multi.py"],
    deps = [
        "//multi:__init__",
    ],
)
