#!/bin/sh

set -e

# Create kubeconfig copy in home dir so mounting works on MacOS
tmp=~/.actl.$RANDOM.$RANDOM.$RANDOM.$$
(umask 077 && mkdir $tmp) || {
    echo "Could not create temporary directory! Exiting." 1>&2
    exit 1
}
trap 'rm -rf $tmp' EXIT

kubectl config view --flatten >> $tmp/kubeconfig

docker run --rm -v=${tmp}/kubeconfig:/kubeconfig:ro -it ark3/actl "$@"
