#!/usr/bin/env bash

# Copyright 2018-2019 Datawire. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License

set -o errexit

source_dir=$(pwd)

if [ \( $(basename $source_dir) != "ambassador" \) -a \( -d "$source_dir/ambassador/docs" \) ]; then
    source_dir="$source_dir/ambassador"
fi

cd $(dirname $0)
root_dir=$(pwd)

if [ -z "$GH_TOKEN" ]; then
    GH_TOKEN=$(keybase fs read /keybase/team/datawireio/secrets/github.d6e-automaton.repo-access.personal-access-token)
fi

if [ -z "$WEBSITE_BRANCH" ]; then
    WEBSITE_BRANCH="master"
fi

if [ -z "$WEBSITE_DIR" ]; then
    WEBSITE_DIR="/tmp/getambassador.io-$WEBSITE_BRANCH"
fi

set -o nounset
set -o xtrace

rm -rf "$WEBSITE_DIR"

git clone --single-branch --branch="$WEBSITE_BRANCH" \
    https://d6e-automaton:${GH_TOKEN}@github.com/datawire/getambassador.io.git \
    "$WEBSITE_DIR"

cd "${WEBSITE_DIR}"

# In the Real World, we use git submodule to update all the docs, but for our purposes here, we're
# not "really" building all the docs -- we just want a single preview.
rm -rf submodules/*
mkdir -p submodules/latest/docs

(cd "$source_dir" && bash ${root_dir}/doc-sync "${WEBSITE_DIR}")

npm install
npm run start
