#!/usr/bin/env bash

# Copyright 2018-2019 Datawire. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License

set -o errexit

if [ -z "$WEBSITE_BRANCH" ]; then
    WEBSITE_BRANCH="master"
fi

if [ -n "$1" ]; then
    WEBSITE_DIR="$1"
elif [ -z "$WEBSITE_DIR" ]; then
    WEBSITE_DIR="/tmp/getambassador.io-${WEBSITE_BRANCH}"
fi

set -o nounset
set -o xtrace

source_dir=$(pwd)

if [ \( $(basename $source_dir) != "ambassador" \) -a \( -d "$source_dir/ambassador/docs" \) ]; then
    source_dir="$source_dir/ambassador"
fi

cd "$WEBSITE_DIR"

# In the Real World, we use git submodule to update all the docs, but for our purposes here, we're
# not "really" building all the docs -- we just want a single preview.
rsync -av "${source_dir}/docs/" submodules/latest/docs

# Since we only want the one preview, toss out links to other versions from the header...
sed -e '/to="\/docs\/[0-9]/d' < src/components/Header/Header.js > H2.js && mv H2.js src/components/Header/Header.js

# ...and in docs-structure.
rm -f docs-structure/docs/[0-9]*
