#!/bin/sh -e

# If DOCKER_REGISTRY is set, use that as the namespace for the build,
# then push to Docker Hub. Otherwise use the specified namespace to
# build, don't push.

DEFAULT_NAMESPACE="$1"
NAME="$2"
VERSION="$3"
TARGET="$4"

HERE=$(dirname $0)
eval $(sh $HERE/get_registries.sh)

if [ -z "${DOCKER_REGISTRY}" ]; then exit 1; fi

docker build -t "${DOCKER_REGISTRY}${NAME}:${VERSION}" "${TARGET}"
docker push "${DOCKER_REGISTRY}${NAME}:${VERSION}"
