#!/bin/sh

kubecontext=$(kubectl config current-context)

if [ "$kubecontext" == "minikube" ]; then
    AMBASSADORURL=$(minikube service --url ambassador 2>/dev/null)
else
    while true; do
        AMBASSADORURL=http://$(kubectl get service ambassador --output jsonpath='{.status.loadBalancer.ingress[0].hostname}' 2>/dev/null)

        if [ $? -eq 0 ]; then
            break
        fi

        sleep 1
    done
fi

echo "export AMBASSADORURL=$AMBASSADORURL"

