#!/bin/sh

# Copyright 2018 Datawire. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License

kubecontext=$(kubectl config current-context)

if [ "$kubecontext" == "minikube" ]; then
    AMBASSADORURL=$(minikube service --url ambassador 2>/dev/null)
else
    while true; do
        errors=0

        IP=$(kubectl get service ambassador --output jsonpath='{.status.loadBalancer.ingress[0].hostname}') 2>/dev/null

        if [ $? != 0 ]; then
            errors=1
        fi

        PORT=$(kubectl get service ambassador --output jsonpath='{.spec.ports[0].port}') 2>/dev/null

        if [ $? != 0 ]; then
            errors=1
        fi

        if [ $errors -eq 0 ]; then
            PROTOCOL='http'

            if [ $PORT == '443' ]; then
                PROTOCOL='https'
            fi

            AMBASSADORURL="${PROTOCOL}://${IP}"

            break
        fi

        sleep 1
    done
fi

echo "export AMBASSADORURL=$AMBASSADORURL"

