#!/bin/sh

set -x

MAPPING="$1"
PREFIX="$2"
SERVICE="$3"
REWRITE="$4"

if [ -z "$MAPPING" -o -z "$PREFIX" -o -z "$SERVICE" ]; then
    echo "Usage: $(basename $0) mapping-name url-prefix service-name [rewrite]" >&2
    exit 1
fi

if [ -z "$REWRITE" ]; then
    REWRITE="/"
fi

if [ -z "$AMBASSADORURL" ]; then
    path=$(dirname $0)
    eval $("$SHELL" "$path/geturl")
fi

curl -v -XPOST -H "Content-Type: application/json" \
      -d "{ \"prefix\": \"/$PREFIX/\", \"service\": \"$SERVICE\", \"rewrite\": \"$REWRITE\" }" \
      "$AMBASSADORURL/ambassador/mapping/$MAPPING"
