#!/bin/sh

SERVICE="$1"

if [ -z "$SERVICE" ]; then
    echo "Usage: $(basename $0) service" >&2
    exit 1
fi

if [ -z "$AMBASSADORURL" ]; then
    path=$(dirname $0)
    eval $("$SHELL" "$path/geturl")
fi

curl -XDELETE "$AMBASSADORURL/ambassador/service/$SERVICE"

