#!/hint/bash

alias echo_on="{ set -x; }"
alias echo_off="{ set +x; } 2>/dev/null"

# shellcheck disable=SC1091
source /etc/profile.d/bash_completion.sh
# shellcheck disable=SC1091
source /usr/local/bin/kube-ps1.sh

alias k=kubectl
complete -F __start_kubectl k

# These are already accomodated by the kubectx/kubens completions.
alias kctx=kubectx
alias kns=kubens

__prompt_info () {
	PS1="$(kube_ps1) ${BUILDER_NAME}:\w $ "
}

old=""

if [ -n "$PROMPT_COMMAND" ]; then
    old="$PROMPT_COMMAND"
fi

PROMPT_COMMAND="__prompt_info;$old"
