########################################
# The ambassador-ea image is the early access image: it's the "normal"
# ambassador image with several extra options turned on.

# It's VERY IMPORTANT to set base_ambassador correctly! We override it
# in the Makefile, but default it to the ambassador stage so maybe we
# have a chance of this Dockerfile working out of the box.

ARG base_ambassador="ambassador"

FROM ${base_ambassador} as ambassador-ea

ENV AMBASSADOR_FAST_RECONFIGURE=true
ENV AMBASSADOR_ENVOY_API_VERSION=V3
