load("@rules_python//python:defs.bzl", "py_binary")
py_binary(
    name = "ambassador",
    srcs = [ ":ambassador.py" ],
    python_version = "PY3",
)
py_binary(
    name = "mockery",
    srcs = [ ":mockery.py" ],
    python_version = "PY3",
)
py_binary(
    name = "grab-snapshots",
    srcs = [ ":grab_snapshots.py" ],
    python_version = "PY3",
)
py_binary(
    name = "ert",
    srcs = [ ":ert.py" ],
    python_version = "PY3",
)
