#!/bin/bash
set -e

which glide > /dev/null 2>&1 && exit 0

if test "Darwin" == "$(uname)"
    then brew install glide
fi

which glide > /dev/null 2>&1 || {
    mkdir -p ./glide

    curl -L https://github.com/Masterminds/glide/releases/download/v0.12.2/glide-v0.12.2-linux-amd64.tar.gz | tar xz -C ./glide --strip-components=1
    chmod 755 -R ./glide

    if which sudo >/dev/null;
        then sudo mv ./glide/glide /usr/local/bin/
    else
        mv ./glide/glide /usr/local/bin/
    fi
}

which glide > /dev/null 2>&1