#!/bin/bash

PROTOC_VER=3.5.1
PROTOC_REL=protoc-"${PROTOC_VER}"-linux-x86_64.zip
pushd /tmp
wget https://github.com/google/protobuf/releases/download/v"${PROTOC_VER}/${PROTOC_REL}"
unzip "${PROTOC_REL}" -d protoc

if which sudo >/dev/null;
    then sudo mv protoc /usr/local && sudo ln -s /usr/local/protoc/bin/protoc /usr/local/bin
else
    mv protoc /usr/local && ln -s /usr/local/protoc/bin/protoc /usr/local/bin
fi
popd
go get -u github.com/golang/protobuf/protoc-gen-go
